spring:
  application:
    name: fileserver
  datasource:
    url: jdbc:mysql://localhost:3306/file_server_db
    username: root
    password:      
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate: 
        cache:
          type: simple
  
        